### ISSUE TITLE
BUILD FAILED with RN 0.39

### ISSUE THREAD

**Issue by tooodooo** [andpor/react-native-sqlite-storage#103]
/Users/~~~~/android/app/src/main/java/~/~/~/MainApplication.java:31: 错误: 找不到符号
                    new SQLitePluginPackage(),
                        ^
  符号: 类 SQLitePluginPackage
1 个错误
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11.694 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

(node:2834) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'message' of undefined
(node:2834) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by itinance** [comment]
@tooodooo I've upgraded our app to the current most recent version 0.39.1 and everything works fine. Have you followed the steps to [install this lib on android](https://github.com/andpor/react-native-sqlite-storage#how-to-use-android) completely?

Remember also settings.gradle and build.gradle. Otherwise show the files please and the steps you have taken.

**Comment by andpor** [comment]
Closed. Issue most likely due to local setup.
