### ISSUE TITLE
Unable to run query using REGEXP

### ISSUE THREAD

**Issue by bulby97** [andpor/react-native-sqlite-storage#151]
Running this query in DB Browser for SQLITE works flawlessly: 
`SELECT * FROM LSGSAT2 WHERE Texte REGEXP  '\b01\b' ORDER BY Livre ASC LIMIT 20`

Can't get it to work in the react-native app, I got no results.

Any ideas ?

**Comment by andpor** [comment]
Has anyone else from the community tried regex based queries?

**Comment by andpor** [comment]
regex does not seem to be a standard function present in SQLite builds. See [this](http://www.sqlite.org/lang_expr.html#regexp)

**Comment by bulby97** [comment]
I see, thank you. Is there any solution ?

**Comment by stoufa06** [comment]
I am trying to found sqlite react native component with support regexp but with no success. I have found cordova phonegap extension that have found solution with Java sqlite connector ([Android-sqlite-connector](https://github.com/liteglue/Android-sqlite-connector)) that supports pcre extension for sqlite instead of default android Database classes. 
Someone could help me and point me how to integrate this in react-native-sqlite-storage.
thank you
