### ISSUE TITLE
undefined is not an object (Evaluating 'NativeModules["SQLite"][method]') help me

### ISSUE THREAD

**Issue by nguyenhatruong** [andpor/react-native-sqlite-storage#154]
![image](https://cloud.githubusercontent.com/assets/20810794/25077083/d7b822fa-2350-11e7-827b-f6d873ae12d2.png)

**Comment by dryganets** [comment]
It looks like you didn't integrate the library into the native shell app correctly.
As you have windows paths I assume you are trying to run android.

On android, you need to add SqlitePackage to the list of the packages of the app.
See step 4 in the readme.
Make sure that you rebuild your app.

**Comment by andpor** [comment]
this is a common error with setup. please follow the manual instructions step by step.

**Comment by SnehalAgrawal** [comment]
I followed the following steps and it is solved now.
1. If you are linking SQLite with `react-native link` then required changes are not done by the linker so you have to do it on your own. Add the required changes mentioned in the [Example of SQLite Database in React Native](https://aboutreact.com/example-of-sqlite-database-in-react-native/).
2.  If everything is well and you have already done all the changes then open the following path
YouSQLiteProject/node_modules/react-native-sqlite-storage/src/android/build.gradle
and replace
compile ‘com.facebook.react:react-native:0.14.+’ (Or another version)
with
implementation ‘com.facebook.react:react-native:+’

As I was using the react-native:0.58.4 and the defined version was react-native:0.14.+, so just removed the version and added plus(+) for the latest version available and it worked for me.

**Comment by iiljazi** [comment]
Hello,
I'm having issues with sqlite on react native. The following is the error being thrown:

`TypeError: null is not an object (evaluating 'NativeModules["SQLite"][method]')`

and it is caused by the openDatabase call here:

```
import { enablePromise, openDatabase } from 'react-native-sqlite-storage';
enablePromise(true);
var db = openDatabase({ name: 'cerberus.db' });
```

If I try to use the connection in that state anyway: e.g. db.executeSql('query', []); it throws the following:

`TypeError: db.executeSql is not a function. (In 'db.executeSql(sql, [])', 'db.executeSql' is undefined)`

Same thing happens if I try to wrap that call in a transaction or even a Promise. It all stems from the fact that the openDatabase is failing. I'm wondering if it's a race condition where I'm trying to use the connection before it is established, however, the openDatabase is not an async function and therefore there's  no option to wait. If anything is obvious here, any recommendations would be highly appreciated!

Thanks,
Ilir
