### ISSUE TITLE
Example to access prepopulated database

### ISSUE THREAD

**Issue by lmiller1990** [andpor/react-native-sqlite-storage#164]
Hi,

I tried following the documentation to access a prepopated sqlite database but no luck. I have tried making www folder, changing the database name and filename to be the same. I am developing and ios app.

Is there any chance of an example project that loads and reads from a pre populated database?

edit just found this https://github.com/andpor/react-native-sqlite-storage-examples/tree/master/PrepopulatedDatabaseExample

Will give it a shot and report back. Seems like a problem with compatibility with react native .44. Was there a link to this from the main readme?

**Comment by BrendonPierson** [comment]
Just ran into this same issue and found the solution in the example.
When following the instructions exactly where the file was the same name as the db and in the www folder, I finally got the connection working by adding the location prop to the config:
ie:
`{name: 'test.db', createFromLocation : "~example.db", location: 'Library'}`
Hope that helps.

**Comment by lmiller1990** [comment]
@BrendonPierson thanks a lot. I'll give this a shot. I thought "Library" would refer to a location on my machine, not in the app. The documentation is a bit confusing and inconsistent (at least I had trouble with it).

If I get it working I'll try to write up a blog post with some more recent sample code and info. Thanks for your help, will get back if this works for me or not.

**Comment by mike-niemand** [comment]
I simply don't seem to be able to get this to work on **Android**. I've tried all options listed. My call is basically:

`SQLite.openDatabase({name: "data.db", createFromLOcation: "~data.db"}, this.openCB, this.errorCB);`

Where the data.db file is in one of:

1) Project root
2) www folder in project root
3) android/app/src/main/assets

The database never copies over. Am I missing something basic?

**Comment by andpor** [comment]
These are the instructions from Readme:
  1.SQLite.openDatabase({name : "testDB", createFromLocation : 1}, okCallback,errorCallback);
  // default - if your folder is called www and data file is named the same as the dbName - testDB in this example


  2.SQLite.openDatabase({name : "testDB", createFromLocation : "~data/mydbfile.sqlite"}, okCallback,errorCallback);
  // if your folder is called data rather than www or your filename does not match the name of the db
  

3.SQLite.openDatabase({name : "testDB", createFromLocation : "/data/mydbfile.sqlite"}, okCallback,errorCallback);
  // if your folder is not in app bundle but in app sandbox i.e. downloaded from some remote location.
  
Note: For Android, the www directory is always relative to the assets directory for the app: src/main/assets

Only #1 hints the implicit connection between source filename and database name. The other two flavors do not but #2 expects a folder name or directory name right after ~, so your example is not quite right since you reference the source file directly. I would put it is some 'data' directory and modify the access path in db open to ~data/your_file_name.

**Comment by paldepind** [comment]
@andpor 

> #2 expects a folder name or directory name right after ~, so your example is not quite right since you reference the source file directly.

Don't you specify a source file directly [here as well](https://github.com/andpor/react-native-sqlite-storage-examples/blob/master/PrepopulatedDatabaseExample/index.ios.js#L26)? Is that incorrect?

**Comment by andpor** [comment]
I have to look in the code again to double check....

**Comment by domih** [comment]
The syntax _SQLite.openDatabase({name : "testDB", createFromLocation : 1}, okCallback,errorCallback);_ works AOK on Android but... if you screwed around with failed attempts, uninstall the app and try again, then it works :-)

**Comment by fahadhaq** [comment]
I am having the same problem. I have followed the example on how to use a pre populated DB but cant seem to get it work on a real device.

I have created the www folder as instructed and gone through the instructions several times.

![unnamed](https://user-images.githubusercontent.com/2104888/33657078-09043bfc-dadd-11e7-8e83-d67273ddb3a5.png)

but when I run the following code I get an error saying there no table named DeviceInf

```
let db = SQLite.openDatabase({ name: "StudentCard.sqlite", createFromLocation: 1 }, openCB, errorCB);
db.transaction((tx) => {
	tx.executeSql('SELECT * from Deviceinfo where isCurrent = 1', [], (tx, results) => {
		console.log("Query completed");
}
```

Can some one please explain what I am doing wrong. Any help would be greatly appriciated

**Comment by andpor** [comment]
in my original response I said:

_1.SQLite.openDatabase({name : "testDB", createFromLocation : 1}, okCallback,errorCallback);
// default - if your folder is called www and data file is named the same as the dbName - testDB in this example_

You coded "StudentCard.sqlite" in your openDatabase...you data file is NOT the same - it seems to be "studentcard.sqlite"

**Comment by andpor** [comment]
@paldepind - you have several options for providing differently named files. I listed the flavors of API calls in one of my earlier responses.

**Comment by SnehalAgrawal** [comment]
After following the documentation and help from this thread finally I am able to load a pre-populated database in Android and IOS Both.
Please make a directory named www and place the database into it. This will be the directory which we will <strong>copy</strong> in Android and IOS.

<img class="aligncenter wp-image-4259 size-full" src="https://aboutreact.com/wp-content/uploads/2019/03/Screenshot-2019-03-01-at-8.35.24-PM.png" alt="" width="733" height="184" />

Now we have to copy this database in different places for Android and IOS because default places to put the database is different for Android and IOS. Please be sure to put the database on the below-mentioned places.
<h2>Placing of Pre-populated Database in Android</h2>
1. In case of Android copy the www directory into android &gt; app &gt; src &gt; main &gt; assets

<a href="https://aboutreact.com/wp-content/uploads/2019/03/Screenshot-2019-03-01-at-8.38.26-PM.png"><img class="aligncenter wp-image-4260 size-full" src="https://aboutreact.com/wp-content/uploads/2019/03/Screenshot-2019-03-01-at-8.38.26-PM.png" alt="" width="1267" height="186" /></a>

2. You can also copy using Android Studio. 

<a href="https://aboutreact.com/wp-content/uploads/2019/03/Screenshot-2019-03-01-at-8.39.01-PM.png"><img class="aligncenter wp-image-4261 size-full" src="https://aboutreact.com/wp-content/uploads/2019/03/Screenshot-2019-03-01-at-8.39.01-PM.png" alt="" width="330" height="279" /></a>
<h2>Placing of Pre-populated Database in IOS</h2>
1. Open your xcodeproj in Xcode.

<a href="https://aboutreact.com/wp-content/uploads/2019/03/Screenshot-2019-03-01-at-8.42.00-PM.png"><img class="aligncenter wp-image-4262 size-full" src="https://aboutreact.com/wp-content/uploads/2019/03/Screenshot-2019-03-01-at-8.42.00-PM.png" alt="" width="605" height="131" /></a>

2. After opening the project right click on the Project folder (SQLiteExample in this case) and select Add Files

<a href="https://aboutreact.com/wp-content/uploads/2019/03/Screenshot-2019-03-01-at-8.42.40-PM.png"><img class="aligncenter wp-image-4263 size-full" src="https://aboutreact.com/wp-content/uploads/2019/03/Screenshot-2019-03-01-at-8.42.40-PM.png" alt="" width="364" height="312" /></a>

3. Navigate to www directory and select www directory with create folder references and SQLiteExample. Then click Add.

<a href="https://aboutreact.com/wp-content/uploads/2019/03/Screenshot-2019-03-01-at-8.43.40-PM.png"><img class="aligncenter wp-image-4264 size-full" src="https://aboutreact.com/wp-content/uploads/2019/03/Screenshot-2019-03-01-at-8.43.40-PM.png" alt="" width="802" height="364" /></a>

4. You can see the added directory in the project structure.

<a href="https://aboutreact.com/wp-content/uploads/2019/03/Screenshot-2019-03-01-at-8.44.49-PM.png"><img class="aligncenter wp-image-4265 size-full" src="https://aboutreact.com/wp-content/uploads/2019/03/Screenshot-2019-03-01-at-8.44.49-PM.png" alt="" width="272" height="164" /></a>

Here we have done all the configuration for the pre-populated database. 
Now to open the database you can use the following line. 
(Here in my case pre-populated database name is user_db.db you can change with your database name)
<pre><code>var db = openDatabase({ name: 'user_db.db', createFromLocation : 1});</code></pre>

If you still have some issue then you can see this [Example to Load Pre Populated SQLite Database in React Native](https://aboutreact.com/example-of-pre-populated-sqlite-database-in-react-native/).

**Comment by holynation** [comment]
@snehalAgrawal, thanks so much. After much hours spent doing this, yours seems to be the only option working correctly. I only added this object (location:Library) to the openDatabase parameter.
Thank you once again

**Comment by holynation** [comment]
If you are facing any issue concerning this, kindly follow @snehalAgrawal step by step method. It really worked out.

**Comment by JOJ0** [comment]
> ```
> var db = openDatabase({ name: 'user_db.db', createFromLocation : 1});
> ```

As @holynation already mentioned, above is not sufficient. I also had to add location:'Library' to the line to make @SnehalAgrawal solution work:

`var db = openDatabase({ name: 'user_db.db', createFromLocation : 1, location:'Library'});`

Hope that helps someone save some hours ;-)

all the best
Jojo

**Comment by SnehalAgrawal** [comment]
@JOJ0 Have you visited this https://aboutreact.com/example-of-pre-populated-sqlite-database-in-react-native/ ???
I have mentioned there.

**Comment by JOJ0** [comment]
HI @SnehalAgrawal,
yes, this is is the sqlite step by step guide I was working with. Very nice tutorial, but the essential part: location: 'Library' unfortunately is also missing there. Maybe you could add it to the example code so others don't have to fiddle around for hours like me as well. I am currently working iOS only, not sure if this is necessary with Android as well.
Thanks a lot and all the best :-)
Jojo

**Comment by SnehalAgrawal** [comment]
@JOJ0 Sorry but I have added the library in HomeScreen.js
var db = openDatabase({ name: 'user_db.db', createFromLocation : 1});

Is there anything else that you are talking about?

**Comment by JOJ0** [comment]
please have a look at my first post in this thread again ;-) 
this is how the openDatabase line has to be in my case and also in @holynation's to make it work:

`var db = openDatabase({ name: 'user_db.db', createFromLocation : 1, location:'Library'});`

**Comment by JOJ0** [comment]
Hi again @SnehalAgrawal I did some research and read the original docs again. Here it describes what the location: 'Library' parameter does. Obviously as I already guessed it is relevant on iOS only: 

https://github.com/andpor/react-native-sqlite-storage#user-content-opening-a-database

Still I'd say it would be a very valuable addition to your tutorial. It was the one thing that would have saved me time and others will certainly benefit from it.

all the best
Jojo

**Comment by holynation** [comment]
@jojo, it is true that one needed to add location: library to make it work correctly

**Comment by JOJ0** [comment]
> 
> 
> @jojo, it is true that one needed to add location: library to make it work correctly

are you on iOS only? or also Android?
thanks! :-)

**Comment by nadiacq** [comment]
Me han salvado Los amo <3

**Comment by holynation** [comment]
> > @jojo, it is true that one needed to add location: library to make it work correctly
> 
> @holynation are you on iOS only? or also Android?
> thanks! :-)

i am on android

**Comment by holynation** [comment]
> > > @jojo, it is true that one needed to add location: library to make it work correctly
> > 
> > 
> > @holynation are you on iOS only? or also Android?
> > thanks! :-)
> 
> i am on android

the same goes for android users

**Comment by hyumus** [comment]
SQLite.openDatabase({name:"testDB.sqlite3",createFromLocation:1,location:'Library'}) . 
this solved my problem. testDB.sqlite3 file size is 24 MB. testDB.sqlite and testDB.db not working, but testDB.sqlite3 is working.

**Comment by ShivamJoker** [comment]
@SnehalAgrawal you should make a PR for updating readme with all that instructions.
Thanks again for solution

**Comment by infinitbility** [comment]
When you want pre-populate database then every time you have to create a new database file and delete previous database or re build application.

check out below documentation

https://infinitbility.com/react-native-sqlite-storage-examples-of-query
