### ISSUE TITLE
Can't open database from Android root directory .

### ISSUE THREAD

**Issue by Symous** [andpor/react-native-sqlite-storage#167]
I create a folder named dbFolder in Android root directory.

ps: the root directory is the external storage directory which we can get from native code:
```java
Environment.getExternalStorageDirectory().
```
then I copy my database file into it and try to open it by:

```js
open(){
      db=SQLiteStorage.openDatabase(
        {name:'mydb',createFromLocation:'/storage/emulated/0/dbFolder/mydb'},
        ()=>{
          this.successCB();
        },
        (err)=>{
          this.errorCB(err);
        }
      )
    },
``` 

But after I invoke this neither success callback nor error callback was invoked.

**Comment by andpor** [comment]
Step 6 - Adjust openDatabase call

Modify you openDatabase call in your application adding createFromLocation param. If you named your database file in step 2 'testDB' the openDatabase call should look like something like this:

  ...
  1.SQLite.openDatabase({name : "testDB", createFromLocation : 1}, okCallback,errorCallback);
  // default - if your folder is called www and data file is named the same as the dbName - testDB in this example


  2.SQLite.openDatabase({name : "testDB", createFromLocation : "~data/mydbfile.sqlite"}, okCallback,errorCallback);
  // if your folder is called data rather than www or your filename does not match the name of the db
  

3.SQLite.openDatabase({name : "testDB", createFromLocation : "/data/mydbfile.sqlite"}, okCallback,errorCallback);
  // if your folder is not in app bundle but in app sandbox i.e. downloaded from some remote location.



For Android, the www directory is always relative to the assets directory for the app: src/main/assets
