### ISSUE TITLE
Use SQLitePlugin in native code

### ISSUE THREAD

**Issue by cavarzan** [andpor/react-native-sqlite-storage#297]
Is possible to use the `SQLitePlugin` in an native Android / iOS code to perform queries and sql operations? Is any example of it?

I'm trying to execute a background sync and we want to do the synchronization in background mode, to allow periodic updates and keep the sync running even if the app goes to background.

I think that one possible solution is extends `SQLitePlugin` and create a custom package, make the method public available and share the sqlite instance between RN and native code (at least in android).

Thanks!

**Comment by AMAISGOD** [comment]
Hi,
I try React Native in last 6 month ago in interactive app for android By sqlite database. I have big problems and try to solve them but at last I Found React Native is so hard to my purposes because my app need to get data from database in many times but handle them and UI was so complex !
I leave react and back to java, I hear some thing about Flutter/ Dart  maybe can help you !!
Good Luck

**Comment by cavarzan** [comment]
@AMAISGOD 
I think that your comment is personal opinion of RN and don't help in this issue.
Thanks anyway!

**Comment by andpor** [comment]
that comment was ridiculous so I deleted it. You can try to use the plugin directly as long as you adhere to the API I suppose although there is a LOT of glue code written in JS...
