### ISSUE TITLE
ReadableMap converter error in react-native 0.14+

### ISSUE THREAD

**Issue by zhuchaowe** [andpor/react-native-sqlite-storage#3]
in react-native 0.13+ the bridge name spelling mistake 
`import com.facebook.react.bridge.ReadableMapKeySeyIterator;`
but have modifyed in react-native 0.14+ 
`import com.facebook.react.bridge.ReadableMapKeySetIterator;`

**Comment by barbarosh** [comment]
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React: Exception in native call from JS
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React: java.lang.RuntimeException: Could not invoke SQLite.open
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:119)
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:143)
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:64)
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at com.facebook.react.bridge.CatalystInstance$NativeModulesReactCallback.call(CatalystInstance.java:366)
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at android.os.Handler.handleCallback(Handler.java:739)
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at android.os.Handler.dispatchMessage(Handler.java:95)
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at android.os.Looper.loop(Looper.java:148)
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at com.facebook.react.bridge.queue.MessageQueueThread$1.run(MessageQueueThread.java:137)
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at java.lang.Thread.run(Thread.java:818)
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:  Caused by: java.lang.reflect.InvocationTargetException
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at java.lang.reflect.Method.invoke(Native Method)
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:106)
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:143) 
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:64) 
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at com.facebook.react.bridge.CatalystInstance$NativeModulesReactCallback.call(CatalystInstance.java:366) 
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at android.os.Handler.handleCallback(Handler.java:739) 
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at android.os.Handler.dispatchMessage(Handler.java:95) 
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at android.os.Looper.loop(Looper.java:148) 
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at com.facebook.react.bridge.queue.MessageQueueThread$1.run(MessageQueueThread.java:137) 
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at java.lang.Thread.run(Thread.java:818) 
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:  Caused by: java.lang.NoSuchMethodError: No interface method keySetIterator()Lcom/facebook/react/bridge/ReadableMapKeySeyIterator; in class Lcom/facebook/react/bridge/ReadableMap; or its super classes (declaration of 'com.facebook.react.bridge.ReadableMap' appears in /data/app/com.reactapp-1/base.apk)
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at org.pgsqlite.SQLitePluginConverter.reactToJSON(SQLitePluginConverter.java:26)
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at org.pgsqlite.SQLitePlugin.open(SQLitePlugin.java:94)
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at java.lang.reflect.Method.invoke(Native Method) 
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:106) 
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:143) 
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:64) 
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at com.facebook.react.bridge.CatalystInstance$NativeModulesReactCallback.call(CatalystInstance.java:366) 
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at android.os.Handler.handleCallback(Handler.java:739) 
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at android.os.Handler.dispatchMessage(Handler.java:95) 
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at android.os.Looper.loop(Looper.java:148) 
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at com.facebook.react.bridge.queue.MessageQueueThread$1.run(MessageQueueThread.java:137) 
11-16 18:47:25.182 10228-14412/com.reactapp E/unknown:React:     at java.lang.Thread.run(Thread.java:818)

**Comment by andpor** [comment]
Thanks for the fix!
