### ISSUE TITLE
MainApplication.java:XY: error: package org.pgsqlite does not exist import org.pgsqlite.SQLitePluginPackage; 

### ISSUE THREAD

**Issue by sinodko** [andpor/react-native-sqlite-storage#320]
I'm not able to use sqlite-storage with the newest react-native version 0.58.

    \MainApplication.java:XY: error: package org.pgsqlite does not exist import org.pgsqlite.SQLitePluginPackage; 

I tried all the three options,, `compile`, `implementation` and `annotationProcessor`. Only using `implementation` got me through this error but then some other weird errors did show up... 

    > Android dependency 'com.android.support:support-v4' has different version for the compile (23.0.1) and runtime (26.1.0) classpath. You should manually set the same version via DependencyResolution

Does anyone have any suggestions?

**Comment by jbcullis** [comment]
I've been having similar issues and here are my findings:

error: package org.pgsqlite does not exist - this one only happened once and it was because the folder didn't exist in the node modules.

Android dependency 'com.android.support:support-v4' - In my case, this error was due to react-native-camera and the solution was to change 

implementation project(':react-native-camera') 

to:

implementation (project(':react-native-camera')) {
        exclude group: "com.android.support"
    }
implementation "com.android.support:exifinterface:+"
implementation "com.android.support:support-annotations:+"
implementation "com.android.support:support-v4:+"


So, I started working backward and found that if I init a brand new app and only install react-native-sqlite-storage, then go through the android setup and the app will spit out errors almost like it's broken react:

error: cannot find symbol import com.facebook.react.ReactApplication;
error: cannot find symbol import com.facebook.react.ReactNativeHost;

**Comment by sinodko** [comment]
@jbcullis wierd that I dont have react-native-camera package installed :/ So you did solve the issue for yourself?

**Comment by jbcullis** [comment]
I was upgrading the app from 0.52.0 and don't really have time to wait for a fix so I rolled back to 0.57.8 and now have a working build. Reading the 0.58.X notes it looks like a lot of things changed in react-native.

**Comment by sinodko** [comment]
hopefully somebody will look into it asap :) but thanks!

**Comment by DavidKuennen** [comment]
Having the same issue.

**Comment by sinodko** [comment]
@DavidKuennen let me know if you solve it pls

**Comment by DavidKuennen** [comment]
I solved it like this: https://github.com/andpor/react-native-sqlite-storage/pull/324

Let me know if it worked for you as well.

**Comment by sinodko** [comment]
it seems to be working! Thank you so much <3

**Comment by Sotiris-k** [comment]
I have to add that the PR of @DavidKuennen is what fixed my problem with RN 0.58

Thank you so much!

**Comment by oguzhanakbolat** [comment]
dependencies {
    implementation "com.facebook.react:react-native:+" 
}

to 

dependencies {
    implementation "com.facebook.react:react-native:0.58.5" 
}

Solved the problem this way

**Comment by sinodko** [comment]
Solved.
