### ISSUE TITLE
Transactions don't rollback when a statement fails and Promises are enabled

### ISSUE THREAD

**Issue by tvau** [andpor/react-native-sqlite-storage#39]
When promises are enabled, transactions don't rollback if an executeSql statement fails.

For example:
``` SQLite.enablePromise(true);
  try {
    db = await SQLite.openDatabase('test.db');
    await db.transaction(tx => {
        tx.executeSql('INCORRECT SQL');
    });
  }
  catch (e) {
   // Never called, the transaction has been committed
    console.log(e);
  } 
```

The issue is that this catch block that can [abort](https://github.com/andpor/react-native-sqlite-storage/blob/master/lib/sqlite.core.js#L446l) the transaction is not called when Promises are enabled.
[handleStatementFailure](https://github.com/andpor/react-native-sqlite-storage/blob/master/lib/sqlite.core.js#L436) does not throw because with promises because an [error handler](https://github.com/andpor/react-native-sqlite-storage/blob/master/sqlite.js#L65) is always provided.

When using callbacks, the transaction is aborted but the error message is incorrectly wrapped in [this](https://github.com/andpor/react-native-sqlite-storage/blob/master/lib/sqlite.core.js#L417).

Maybe transaction objects (tx in example above) should be different in a transaction context and not return promises or expect errors/success callbacks (and the transaction method expects all statements to be enlisted [synchronously](https://github.com/andpor/react-native-sqlite-storage/blob/master/lib/sqlite.core.js#L320)) . Any failure should be available in the error callback/catch promise handler of the encompassing transaction.

**Comment by andpor** [comment]
unfortunately i updated the code and your links to lines are no longer valid. Can you perhaps update them so I can take a look at the issue?

**Comment by andpor** [comment]
Yes, this looks like a bug to me.

@brodybits Chris looking at the code there is an issue in how a transaction failure is handled. When a constituent stmt fails the handleStatementFailure is called attempting to callback on error handler for that particular stmt. This code is weird as it will throw an exception on the grounds of callback not being there rather than transaction failing. So for plain callback implementation, which is the basis for your plugin, the transaction will be aborted with misleading error message. Since I also provided a Promise interface, the transaction is not getting aborted at all since I provide a default internal error handler.

I have a fix in mind. Perhaps you can take a look and validate. 

I think when transaction fails it is fine to do try/catch around stmt success/failure handler but the exception should be eaten up and txFailure = newSQLError(err); should be always generated right after exception is consumed.

**Comment by andpor** [comment]
@tvau I have applied a fix - can you please give it a try and tell me how it is holding up?
@brodybits - Chris can you take a look at let me know your thoughts?

**Comment by tvau** [comment]
@andpor  I tried the fix (I copied the latest sqlite.core.js in my local node_module) and it's working fine with callbacks, the error is no longer wrapped in a 'a statement error callback did not return false' error. Thanks for that !

For promises it works too, but I get the following message in the emulator:
![screenshot from 2016-03-27 17-28-58](https://cloud.githubusercontent.com/assets/17928177/14066099/85004252-f441-11e5-85f2-2884f65ad951.png)

This is due to the fact that the [reject](https://github.com/andpor/react-native-sqlite-storage/blob/master/sqlite.js#L63) of the `tx.executeSql` promise is not handled. I can avoid this message by adding a catch to the executesql call:

```
tx.executeSql('INCORRECT SQL').catch(() => {});
```

But I am not sure if it should be expected since it is not necessary when using callbacks.

**Comment by andpor** [comment]
That should be trivial to fix. I will test it out later on today.

**Comment by andpor** [comment]
@tvau - try now - get the latest sqlite.js

**Comment by tvau** [comment]
@andpor It works , thanks :smile:

**Comment by andpor** [comment]
@brodybits - Chris I think this fix here could be leveraged in your plugin since transaction abort does suffer the same way.

**Comment by andpor** [comment]
@tvau - thanks for reporting this issue and providing such a great analysis...much appreciated.
