### ISSUE TITLE
[Question] Are you even supporting this package anymore?

### ISSUE THREAD

**Issue by mjstelly** [andpor/react-native-sqlite-storage#436]
It looks like this project has been abandoned. Is that so? No updates in the past year, unresolved issues were closed.

Any thoughts on whether or not we can expect any support or updates any time soon?

**Comment by andpor** [comment]
@mjstelly project is active. No updates in the past year? See [https://github.com/andpor/react-native-sqlite-storage/releases](releases)

Which UNRESOLVED issue that were closed are you referring to?

Work is being done as time permits.

**Comment by mjstelly** [comment]
Issues #48 and #288 are specific examples. The first being the most relevant. Fortunately, a colleague of mine was able to resolve the issue in his branch. I didn't have time to analyze what he did differently. I just picked up where he left off. I understand that this is an OSS project and my question was unnecessarily aggressive. I apologize. I let my frustration and need for a working solution cloud my judgment. 

If there is something on which I can help, I will. It's better to be part of the solution than part of the problem. Thanks for your response.

**Comment by andpor** [comment]
@mjstelly if you read carefully, issue #48 has not been closed. It is really not a library issue but a bad set up issue. Questions like this are better to be raised on stack overflow rather than here where it get better community support/answers. Issue #288 was closed due to lack of followup information. I did make a few suggestions pointing potential code issue outside of library. There has never been any kind of followup for months so I concluded the issue was not a real problem.

I do try to invest time to address real issue unfortunately I do not have much time on my hands to be experimenting and guessing what the user's setup may cause the problem each time.

Lack of precise information is frequently the reason why things do not get attention. There are both JS logs and native logs written by the library and most of the time a one liner without any debugging information is not going to suffice. If the end user has not had invested time to troubleshoot and provide as much precise information needed to replicate the issue, why would you expect me to do it for them?

On top it, there are 4 demo files showing all aspects of library functionality. They all work, have been tested and most folks have no problems. There will be exceptions of course, but if someone is not successful setting up the module where 99% of community has no problems they ought to be able to articulate and describe exact issue and provide means of replicating the problem.

**Comment by mjstelly** [comment]
> On top of it, there are 4 demo files showing all aspects of library functionality. They all work, have been tested and most folks have no problems. 

I agree with a great many of your assertions. A lot of the issues I'm experiencing stem from my lack of understanding of the module's API. With that said, I think the responsibility lay with the author to rectify areas of misunderstanding. Of course, the reporter has to meet you halfway. Far too many folks think we're mind readers here to magically solve their coding issues.

But hey, we're all learning here. I appreciate your efforts. I will do what I can to meet you in the middle to resolve any issues I have.

**Comment by andpor** [comment]
@mjstelly "responsibility lay with the author to rectify" ? This is getting better and better....I think once you start paying someone hard cash we can discuss the context of responsibility :)

**Comment by mjstelly** [comment]
Touchè. Point taken. I'll stick to raising substantive issues rather than philosophical ones.
