### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by ZhuFengdaaa** [andpor/react-native-sqlite-storage#60]
I build with `react-native run-ios` in macbook terminal, with `npm install react-native-sqlite-storage` installed before. 

The build process success until the following command: 

`Ld build/Build/Products/Debug-iphonesimulator/test.app/test normal x86_64`

```
Undefined symbols for architecture x86_64:
  "_sqlite3_bind_double", referenced from:
      -[SQLite bindStatement:withArg:atIndex:] in libSQLite.a(SQLite.o)
  "_sqlite3_bind_int", referenced from:
      -[SQLite bindStatement:withArg:atIndex:] in libSQLite.a(SQLite.o)
  "_sqlite3_bind_int64", referenced from:
      -[SQLite bindStatement:withArg:atIndex:] in libSQLite.a(SQLite.o)
  "_sqlite3_bind_null", referenced from:
      -[SQLite bindStatement:withArg:atIndex:] in libSQLite.a(SQLite.o)
  "_sqlite3_bind_text", referenced from:
      -[SQLite bindStatement:withArg:atIndex:] in libSQLite.a(SQLite.o)
  "_sqlite3_close", referenced from:
      -[SQLite close:success:error:] in libSQLite.a(SQLite.o)
      -[SQLite dealloc] in libSQLite.a(SQLite.o)
  "_sqlite3_column_blob", referenced from:
      -[SQLite executeSqlWithDict:andArgs:] in libSQLite.a(SQLite.o)
  "_sqlite3_column_bytes", referenced from:
      -[SQLite executeSqlWithDict:andArgs:] in libSQLite.a(SQLite.o)
  "_sqlite3_column_count", referenced from:
      -[SQLite executeSqlWithDict:andArgs:] in libSQLite.a(SQLite.o)
  "_sqlite3_column_double", referenced from:
      -[SQLite executeSqlWithDict:andArgs:] in libSQLite.a(SQLite.o)
  "_sqlite3_column_int64", referenced from:
      -[SQLite executeSqlWithDict:andArgs:] in libSQLite.a(SQLite.o)
  "_sqlite3_column_name", referenced from:
      -[SQLite executeSqlWithDict:andArgs:] in libSQLite.a(SQLite.o)
  "_sqlite3_column_text", referenced from:
      -[SQLite executeSqlWithDict:andArgs:] in libSQLite.a(SQLite.o)
  "_sqlite3_column_type", referenced from:
      -[SQLite executeSqlWithDict:andArgs:] in libSQLite.a(SQLite.o)
  "_sqlite3_create_function", referenced from:
      -[SQLite open:success:error:] in libSQLite.a(SQLite.o)
  "_sqlite3_errcode", referenced from:
      +[SQLite captureSQLiteErrorFromDb:] in libSQLite.a(SQLite.o)
  "_sqlite3_errmsg", referenced from:
      +[SQLite captureSQLiteErrorFromDb:] in libSQLite.a(SQLite.o)
  "_sqlite3_exec", referenced from:
      -[SQLite open:success:error:] in libSQLite.a(SQLite.o)
  "_sqlite3_finalize", referenced from:
      -[SQLite executeSqlWithDict:andArgs:] in libSQLite.a(SQLite.o)
  "_sqlite3_last_insert_rowid", referenced from:
      -[SQLite executeSqlWithDict:andArgs:] in libSQLite.a(SQLite.o)
  "_sqlite3_open", referenced from:
      -[SQLite open:success:error:] in libSQLite.a(SQLite.o)
  "_sqlite3_prepare_v2", referenced from:
      -[SQLite executeSqlWithDict:andArgs:] in libSQLite.a(SQLite.o)
  "_sqlite3_result_error", referenced from:
      _sqlite_regexp in libSQLite.a(SQLite.o)
  "_sqlite3_result_int", referenced from:
      _sqlite_regexp in libSQLite.a(SQLite.o)
  "_sqlite3_step", referenced from:
      -[SQLite executeSqlWithDict:andArgs:] in libSQLite.a(SQLite.o)
  "_sqlite3_threadsafe", referenced from:
      -[SQLite open:success:error:] in libSQLite.a(SQLite.o)
  "_sqlite3_total_changes", referenced from:
      -[SQLite executeSqlWithDict:andArgs:] in libSQLite.a(SQLite.o)
  "_sqlite3_value_text", referenced from:
      _sqlite_regexp in libSQLite.a(SQLite.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by andpor** [comment]
what is react-native run-ios?

**Comment by andpor** [comment]
@ZhuFengdaaa - please provide more information about your issue. Otherwise I can only close as the plugin seems to work fine for all architectures on iOS, including x86_64.

**Comment by andpor** [comment]
@ZhuFengdaaa  - if I don't hear from you in the next few days I will consider this as non-issue and close it.

**Comment by andpor** [comment]
Closing this for not enough information provided to start troubleshooting. Assume user error rather than problem with the module.

**Comment by ZhuFengdaaa** [comment]
Sorry for replying too late. React native is a framework enable us to build mobile app (both Android and IOS) in react. `react-native run-ios` is the build command that make js code and run the app on IOS device. Now I give up using the `react-native-sqlite-storage` and remove it from package.json and my app build well. Even though I don't know why the error came from. Thanks.

**Comment by andpor** [comment]
@ZhuFengdaaa I am sorry to hear you are having trouble making configuration changes. Without additional information it is hard to even start troubleshooting.

I ran react-native run-ios in my terminal window with the AwesomeProject which includes react-native-sqlite-storage as demo and did not notice any errors...I can only suspect you had inadvertently changed some configuration , namely supported architectures, which could potentially cause the linkage issue..

Again - just guessing since you did not provide any supporting documentation about the issue except for the output from react-native run-ios..

Have you actually completed configuration of the library into your project? Running npm install by itself is only one step...you can refer to documentation about what other steps you must complete before running the app.

>react-native run-ios
Found Xcode project AwesomeProject.xcodeproj
Launching iPhone 6 (9.3)...
Building using "xcodebuild -project AwesomeProject.xcodeproj -scheme AwesomeProject -destination id=E98D0D00-C9A7-4867-B77F-D31A56619B09 -derivedDataPath build"
User defaults from command line:
    IDEDerivedDataPathOverride = /Users/sylwia/AwesomeProject/ios/build

=== BUILD TARGET RCTActionSheet OF PROJECT RCTActionSheet WITH CONFIGURATION Debug ===

Check dependencies

Write auxiliary files
write-file /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/RCTActionSheet.build/Debug-iphonesimulator/RCTActionSheet.build/RCTActionSheet-all-non-framework-target-headers.hmap
write-file /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/RCTActionSheet.build/Debug-iphonesimulator/RCTActionSheet.build/RCTActionSheet.hmap
write-file /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/RCTActionSheet.build/Debug-iphonesimulator/RCTActionSheet.build/RCTActionSheet-all-target-headers.hmap
write-file /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/RCTActionSheet.build/Debug-iphonesimulator/RCTActionSheet.build/RCTActionSheet-generated-files.hmap
/bin/mkdir -p /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/RCTActionSheet.build/Debug-iphonesimulator/RCTActionSheet.build/Objects-normal/x86_64
write-file /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/RCTActionSheet.build/Debug-iphonesimulator/RCTActionSheet.build/Objects-normal/x86_64/RCTActionSheet.LinkFileList
write-file /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/RCTActionSheet.build/Debug-iphonesimulator/RCTActionSheet.build/RCTActionSheet-project-headers.hmap
write-file /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/RCTActionSheet.build/Debug-iphonesimulator/RCTActionSheet.build/RCTActionSheet-own-target-headers.hmap

CompileC /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/RCTActionSheet.build/Debug-iphonesimulator/RCTActionSheet.build/Objects-normal/x86_64/RCTActionSheetManager.o RCTActionSheetManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/sylwia/AwesomeProject/node_modules/react-native/Libraries/ActionSheetIOS
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/sylwia/.nvm/versions/node/v4.2.6/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/sylwia/.nvm"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=111 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=gnu99 -fobjc-arc -fmodules -fmodules-cache-path=/Users/sylwia/AwesomeProject/ios/build/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/sylwia/AwesomeProject/ios/build/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wshadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=7.0 -g -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -iquote /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/RCTActionSheet.build/Debug-iphonesimulator/RCTActionSheet.build/RCTActionSheet-generated-files.hmap -I/Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/RCTActionSheet.build/Debug-iphonesimulator/RCTActionSheet.build/RCTActionSheet-own-target-headers.hmap -I/Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/RCTActionSheet.build/Debug-iphonesimulator/RCTActionSheet.build/RCTActionSheet-all-target-headers.hmap -iquote /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/RCTActionSheet.build/Debug-iphonesimulator/RCTActionSheet.build/RCTActionSheet-project-headers.hmap -I/Users/sylwia/AwesomeProject/ios/build/Build/Products/Debug-iphonesimulator/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I../../React -I../../React/Base -I../../React/Executors -I../../React/Layout -I../../React/Modules -I../../React/Profiler -I../../React/Views -I/Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/RCTActionSheet.build/Debug-iphonesimulator/RCTActionSheet.build/DerivedSources/x86_64 -I/Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/RCTActionSheet.build/Debug-iphonesimulator/RCTActionSheet.build/DerivedSources -Wextra -Wall -F/Users/sylwia/AwesomeProject/ios/build/Build/Products/Debug-iphonesimulator -MMD -MT dependencies -MF /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/RCTActionSheet.build/Debug-iphonesimulator/RCTActionSheet.build/Objects-normal/x86_64/RCTActionSheetManager.d --serialize-diagnostics /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/RCTActionSheet.build/Debug-iphonesimulator/RCTActionSheet.build/Objects-normal/x86_64/RCTActionSheetManager.dia -c /Users/sylwia/AwesomeProject/node_modules/react-native/Libraries/ActionSheetIOS/RCTActionSheetManager.m -o /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/RCTActionSheet.build/Debug-iphonesimulator/RCTActionSheet.build/Objects-normal/x86_64/RCTActionSheetManager.o

Analyze RCTActionSheetManager.m
    cd /Users/sylwia/AwesomeProject/node_modules/react-native/Libraries/ActionSheetIOS
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/sylwia/.nvm/versions/node/v4.2.6/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/sylwia/.nvm"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=111 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=gnu99 -fobjc-arc -fmodules -fmodules-cache-path=/Users/sylwia/AwesomeProject/ios/build/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/sylwia/AwesomeProject/ios/build/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wshadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=7.0 -g -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -D__clang_analyzer__ -Xclang -analyzer-output=plist-multi-file -Xclang -analyzer-config -Xclang path-diagnostics-alternate=true -Xclang -analyzer-config -Xclang report-in-main-source-file=true -Xclang -analyzer-disable-checker -Xclang nullability -Xclang -analyzer-checker -Xclang security.insecureAPI.UncheckedReturn -Xclang -analyzer-checker -Xclang security.insecureAPI.getpw -Xclang -analyzer-checker -Xclang security.insecureAPI.gets -Xclang -analyzer-checker -Xclang security.insecureAPI.mkstemp -Xclang -analyzer-checker -Xclang security.insecureAPI.mktemp -Xclang -analyzer-disable-checker -Xclang security.insecureAPI.rand -Xclang -analyzer-disable-checker -Xclang security.insecureAPI.strcpy -Xclang -analyzer-checker -Xclang security.insecureAPI.vfork -iquote /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/RCTActionSheet.build/Debug-iphonesimulator/RCTActionSheet.build/RCTActionSheet-generated-files.hmap -I/Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/RCTActionSheet.build/Debug-iphonesimulator/RCTActionSheet.build/RCTActionSheet-own-target-headers.hmap -I/Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/RCTActionSheet.build/Debug-iphonesimulator/RCTActionSheet.build/RCTActionSheet-all-target-headers.hmap -iquote /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/RCTActionSheet.build/Debug-iphonesimulator/RCTActionSheet.build/RCTActionSheet-project-headers.hmap -I/Users/sylwia/AwesomeProject/ios/build/Build/Products/Debug-iphonesimulator/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I../../React -I../../React/Base -I../../React/Executors -I../../React/Layout -I../../React/Modules -I../../React/Profiler -I../../React/Views -I/Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/RCTActionSheet.build/Debug-iphonesimulator/RCTActionSheet.build/DerivedSources/x86_64 -I/Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/RCTActionSheet.build/Debug-iphonesimulator/RCTActionSheet.build/DerivedSources -Wextra -Wall -F/Users/sylwia/AwesomeProject/ios/build/Build/Products/Debug-iphonesimulator -MMD -MT dependencies -MF /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/RCTActionSheet.build/Debug-iphonesimulator/RCTActionSheet.build/StaticAnalyzer/RCTActionSheet/RCTActionSheet/normal/x86_64/RCTActionSheetManager.d --analyze /Users/sylwia/AwesomeProject/node_modules/react-native/Libraries/ActionSheetIOS/RCTActionSheetManager.m -o /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/RCTActionSheet.build/Debug-iphonesimulator/RCTActionSheet.build/StaticAnalyzer/RCTActionSheet/RCTActionSheet/normal/x86_64/RCTActionSheetManager.plist

Libtool /Users/sylwia/AwesomeProject/ios/build/Build/Products/Debug-iphonesimulator/libRCTActionSheet.a normal x86_64
    cd /Users/sylwia/AwesomeProject/node_modules/react-native/Libraries/ActionSheetIOS
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/sylwia/.nvm/versions/node/v4.2.6/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/sylwia/.nvm"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static -arch_only x86_64 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -L/Users/sylwia/AwesomeProject/ios/build/Build/Products/Debug-iphonesimulator -filelist /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/RCTActionSheet.build/Debug-iphonesimulator/RCTActionSheet.build/Objects-normal/x86_64/RCTActionSheet.LinkFileList -o /Users/sylwia/AwesomeProject/ios/build/Build/Products/Debug-iphonesimulator/libRCTActionSheet.a

=== BUILD TARGET React OF PROJECT React WITH CONFIGURATION Debug ===
Check dependencies

Write auxiliary files
write-file /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/React-project-headers.hmap
write-file /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/React.hmap
write-file /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/React-own-target-headers.hmap
write-file /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/React-generated-files.hmap
write-file /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/React-all-target-headers.hmap
write-file /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/React-all-non-framework-target-headers.hmap
write-file /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Script-142C4F7F1B582EA6001F0B58.sh
chmod 0755 /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Script-142C4F7F1B582EA6001F0B58.sh
write-file /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Script-006B79A01A781F38006873D1.sh
chmod 0755 /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Script-006B79A01A781F38006873D1.sh
/bin/mkdir -p /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64
write-file /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/React.LinkFileList

one of many...


CompileC /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTConvert+MapKit.o Views/RCTConvert+MapKit.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/sylwia/AwesomeProject/node_modules/react-native/React
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/sylwia/.nvm/versions/node/v4.2.6/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/sylwia/.nvm"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=111 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=gnu99 -fobjc-arc -fmodules -fmodules-cache-path=/Users/sylwia/AwesomeProject/ios/build/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/sylwia/AwesomeProject/ios/build/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wmissing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wconditional-uninitialized -Wno-unknown-pragmas -Wshadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wnewline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -DRCT_DEBUG=1 -DRCT_DEV=1 -DRCT_NSASSERT=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mios-simulator-version-min=7.0 -g -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -iquote /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/React-generated-files.hmap -I/Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/React-own-target-headers.hmap -I/Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/React-all-target-headers.hmap -iquote /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/React-project-headers.hmap -I/Users/sylwia/AwesomeProject/ios/build/Build/Products/Debug-iphonesimulator/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/DerivedSources/x86_64 -I/Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/DerivedSources -Wextra -Wall -F/Users/sylwia/AwesomeProject/ios/build/Build/Products/Debug-iphonesimulator -MMD -MT dependencies -MF /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTConvert+MapKit.d --serialize-diagnostics /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTConvert+MapKit.dia -c /Users/sylwia/AwesomeProject/node_modules/react-native/React/Views/RCTConvert+MapKit.m -o /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTConvert+MapKit.o


Linkage...

Ld build/Build/Products/Debug-iphonesimulator/AwesomeProject.app/AwesomeProject normal x86_64
    cd /Users/sylwia/AwesomeProject/ios
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/sylwia/.nvm/versions/node/v4.2.6/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/sylwia/.nvm"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -L/Users/sylwia/AwesomeProject/ios/build/Build/Products/Debug-iphonesimulator -F/Users/sylwia/AwesomeProject/ios/build/Build/Products/Debug-iphonesimulator -filelist /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/AwesomeProject.build/Debug-iphonesimulator/AwesomeProject.build/Objects-normal/x86_64/AwesomeProject.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=7.0 -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -ObjC -fobjc-arc -fobjc-link-runtime /Users/sylwia/AwesomeProject/ios/build/Build/Products/Debug-iphonesimulator/libSQLite.a /Users/sylwia/AwesomeProject/ios/build/Build/Products/Debug-iphonesimulator/libReact.a /Users/sylwia/AwesomeProject/ios/build/Build/Products/Debug-iphonesimulator/libRCTActionSheet.a /Users/sylwia/AwesomeProject/ios/build/Build/Products/Debug-iphonesimulator/libRCTGeolocation.a /Users/sylwia/AwesomeProject/ios/build/Build/Products/Debug-iphonesimulator/libRCTImage.a /Users/sylwia/AwesomeProject/ios/build/Build/Products/Debug-iphonesimulator/libRCTLinking.a /Users/sylwia/AwesomeProject/ios/build/Build/Products/Debug-iphonesimulator/libRCTNetwork.a /Users/sylwia/AwesomeProject/ios/build/Build/Products/Debug-iphonesimulator/libRCTSettings.a /Users/sylwia/AwesomeProject/ios/build/Build/Products/Debug-iphonesimulator/libRCTText.a /Users/sylwia/AwesomeProject/ios/build/Build/Products/Debug-iphonesimulator/libRCTVibration.a /Users/sylwia/AwesomeProject/ios/build/Build/Products/Debug-iphonesimulator/libRCTWebSocket.a -lsqlite3.0 -Xlinker -dependency_info -Xlinker /Users/sylwia/AwesomeProject/ios/build/Build/Intermediates/AwesomeProject.build/Debug-iphonesimulator/AwesomeProject.build/Objects-normal/x86_64/AwesomeProject_dependency_info.dat -o /Users/sylwia/AwesomeProject/ios/build/Build/Products/Debug-iphonesimulator/AwesomeProject.app/AwesomeProject
ld: warning: object file (/Users/sylwia/AwesomeProject/ios/build/Build/Products/Debug-iphonesimulator/libSQLite.a(SQLite.o)) was built for newer iOS version (8.1) than being linked (7.0)
ld: warning: object file (/Users/sylwia/AwesomeProject/ios/build/Build/Products/Debug-iphonesimulator/libSQLite.a(SQLiteResult.o)) was built for newer iOS version (8.1) than being linked (7.0)

GenerateDSYMFile build/Build/Products/Debug-iphonesimulator/AwesomeProjectTests.xctest.dSYM build/Build/Products/Debug-iphonesimulator/AwesomeProject.app/PlugIns/AwesomeProjectTests.xctest/AwesomeProjectTests
    cd /Users/sylwia/AwesomeProject/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/sylwia/.nvm/versions/node/v4.2.6/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/sylwia/.nvm"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/sylwia/AwesomeProject/ios/build/Build/Products/Debug-iphonesimulator/AwesomeProject.app/PlugIns/AwesomeProjectTests.xctest/AwesomeProjectTests -o /Users/sylwia/AwesomeProject/ios/build/Build/Products/Debug-iphonesimulator/AwesomeProjectTests.xctest.dSYM

Touch build/Build/Products/Debug-iphonesimulator/AwesomeProject.app/PlugIns/AwesomeProjectTests.xctest
    cd /Users/sylwia/AwesomeProject/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/sylwia/.nvm/versions/node/v4.2.6/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/sylwia/.nvm"
    /usr/bin/touch -c /Users/sylwia/AwesomeProject/ios/build/Build/Products/Debug-iphonesimulator/AwesomeProject.app/PlugIns/AwesomeProjectTests.xctest

** BUILD SUCCEEDED **


The following commands produced analyzer issues:
	Analyze Profiler/RCTJSCProfiler.m
	Analyze Modules/RCTUIManager.m
(2 commands with analyzer issues)
Installing build/Build/Products/Debug-iphonesimulator/AwesomeProject.app
Launching org.reactjs.native.example.AwesomeProject
org.reactjs.native.example.AwesomeProject: 32919

**Comment by andpor** [comment]
End user config issue,
