### ISSUE TITLE
[QUESTION] SQL Query Builder

### ISSUE THREAD

**Issue by rops** [andpor/react-native-sqlite-storage#91]
Can you guys recommend any good SQL query builder package that works fine with react-native?

**Comment by andpor** [comment]
I am going to close this since there has been no feedback from community...

**Comment by itinance** [comment]
If i understood the opener correctly, the author is looking for something like CoreData or another ORM-libraries (ORM = Object relational mapping). And i think, this should not be part of this library. I rather recommend to create a new one based on top of this one providing such capabilities (and yes, i'm already thinking about independently from this issue)

**Comment by rops** [comment]
Not really. I was more interesting into some library that helps building SQL queries instead of writing it manually. e.g.

`
tx.executeSql(`SELECT * FROM Employees WHERE id = ${id}`);
//vs
tx.executeSql(employeesTable.select({id: id)
`

Something like https://github.com/brianc/node-sql, which I tried but has some issue with the react-native node environment

**Comment by dantman** [comment]
The only two quality libraries I know of are [Sequelize](http://docs.sequelizejs.com/) (a full ORM) and [knex](http://knexjs.org/) (query builder that can be used with or without a builtin driver). Then there's [Bookshelf](http://bookshelfjs.org/) an ORM built around knex.

I'm currently attempting to use the latter two in a React Native project.

**Comment by rops** [comment]
That's what I was asking for thanks :) knex seems promising! Did you have any issue so far while using it with react-native?

**Comment by mbrgm** [comment]
I tried using both of them with React Native, but it was pretty tedious in either case and I quit before getting any of them to work. They both depend on a 'regular' node.js environment (event, assert, fs, ...), as do some of their dependencies, which had their own issues when used with RN.

I finally found out about [squel](https://hiddentao.com/squel/), which just works™.

**Comment by itinance** [comment]
Why do you hesitate to learn SQL? On iOS and Android is sqlite3 the defacto-sql-standard and this will be so for next years. So there is no reason to use complex abstractions around a query. 
Don't get me wrong please, serious question: why should one use "squel" instead of direct sql?

**Comment by rops** [comment]
I don't think anyone is avoid learning SQL. As I don't think you can use a SQL query string builder without knowing SQL.
It's only a matter of having an API more flexible and robust than string manipulation and concatenation.

**Comment by mbrgm** [comment]
@itinance One reason may be having a layer of abstraction around different flavors of SQL, such as SQLite, MySQL etc. Maybe @rops wants to reuse parts of his code between mobile devices and his backend (which I personally would not recommend). Another reason could be that the query builder syntax may be more appealing than concatenated strings. ES6 template strings work around that issue quite well, though.

**Comment by rops** [comment]
> Another reason could be that the query builder syntax may be more appealing than concatenated strings.
Exactly

>  ES6 template strings work around that issue quite well, though.
I reckon they are ok for simple queries. 

@itinance  I'll give _squel_ a go thanks!

**Comment by mbrgm** [comment]
@rops You're welcome.

**Comment by itinance** [comment]
Thanks for clarifying @rops and @mbrgm! In my humble opinion a unification or just a reuse of the same queries both on device (client) and on backend (server) should be avoided and is not the usecase here. It should be avoided because the data structures on the client could be a small subset instead the large ones on the server. Second, to query the client as a single user could be okay without any huge optimizations, while the same query could be kill the backend under heady load and with a large dataset of millions of records (what would never happen on the client because you serve one user there and not all hundredthousands or millions of your network).

But i see the valid point of having an API to avoid the developers from dealing with string manipulation the right way when dealing with secure sql-statements.

My personal reason for using such an abstraction layer would be a whole ORM-layer where i can deal with objects that represents an entity, and to create, update, find and delete it without to type the queries and the logic around by myself. Anyone interested in this? I plan this as my next library :)

**Comment by mbrgm** [comment]
> In my humble opinion a unification or just a reuse of the same queries both on device (client) and on backend (server) should be avoided and is not the usecase here.

While there may be cases where reuse between client and backend could be feasible, I second your recommendation.

> My personal reason for using such an abstraction layer would be a whole ORM-layer where i can deal with objects that represents an entity, and to create, update, find and delete it without to type the queries and the logic around by myself. Anyone interested in this? I plan to create a library around this topic, specific for RN-world.

I tried Sequelize for the same reasons you mentioned, but as I wrote above, it seemed to be too tightly coupled to node.js environments. I would be interested, but I would favor a non-RN-specific approach (which can also be used in the browser or node.js) even more.

**Comment by dantman** [comment]
@rops
> That's what I was asking for thanks :) knex seems promising! Did you have any issue so far while using it with react-native?

@mbrgm
> I tried using both of them with React Native, but it was pretty tedious in either case and I quit before getting any of them to work. They both depend on a 'regular' node.js environment (event, assert, fs, ...), as do some of their dependencies, which had their own issues when used with RN.

Knex and Bookshelf did have some issues specific to ReactNative that needed some fixing.

Knex actually already supports WebSQL and browserify, it just needed a tweak because react-native handles the `browser` field slightly differently than Browserify which was causing Knex's rules intended to hide things that require the node environment from the browser packagers. I also had to separately install some of the browser compat packages on npm like `stream`. I submitted a pull request for the former which has already been merged into knex.

Bookshelf had its own issue, mostly a minor one related to the `.babelrc` file which needs to be moved to the `src/` directory because ReactNative is trying to compile pre-compiled sources in `lib/` and the .babelrc refers to a transform that is only part of the dev dependencies. The pull request for that fix hasn't been merged yet. Though alternatively you could workaround that just by manually installing that transform.

And finally I had to write a Knex driver for react-native-sqlite-storage, which was mostly just extending the Sqlite3 driver class and copying a little bit from the WebSql driver class.
https://gist.github.com/dantman/59488c2d8bb2b4c59efda99a0040d16c

**Comment by mbrgm** [comment]
> Knex actually already supports WebSQL and browserify, it just needed a tweak because react-native handles the browser field slightly differently than Browserify which was causing Knex's rules intended to hide things that require the node environment from the browser packagers. I also had to separately install some of the browser compat packages on npm like stream. I submitted a pull request for the former which has already been merged into knex.

I also had some issues with the 'supports-color' package, which expected a proper global `process` variable containing a field for `argv`. However, this was not there as it seemed to be spawned in a separate thread, originating at `debugWorker.js`. I didn't investigate any further from there.

@dantman The rest of what you described sounds fantastic. Would you mind providing an example project, just containing a vanilla RN project with all the tweaks you described to successfully import knex and bookshelf? I think it would be helpful to many people reading this thread.

**Comment by dantman** [comment]
> I also had some issues with the 'supports-color' package, which expected a proper global process variable containing a field for argv. However, this was not there as it seemed to be spawned in a separate thread, originating at debugWorker.js. I didn't investigate any further from there.

This one was fixed by importing `'react-native-browser-builtins/react-native/process'` from `react-native-browser-builtins` as a polyfill.

I'm waiting for Bookshelf to merge and release my pull request.

**Comment by tslater** [comment]
I'm linking https://github.com/bookshelf/bookshelf/pull/1470 for reference. 

Dartman, is there anyway you could provide a simple RN example with just Knex (without bookshelf)?
